# Generated by Django 3.2 on 2021-05-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_product_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_gain',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
