# Generated by Django 3.2 on 2021-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_product_gain_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('calories', models.IntegerField(default=0)),
                ('ingridents', models.CharField(max_length=300)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pub_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
